Update rules to get object spread and recommended rules
taskcluster/eslint-config-taskcluster pull request #4
Opened 2018-02-07 18:57 UTC by imbstack

Node > 8.6.0 appears to have object spread built in, but our eslint rules do not allow it at the moment. I would like to use it in some work I'm doing and we use it all over the place in tools so I figured may as well add it.

While I was at it, I saw that our eslint config misses a lot of useful rules such as `no-unused-vars` and `no-undef`, so I added the `eslint:recommended` rules. This will create a decent amount of work when upgrading since a lot of these don't have `--fix` abilities, but it seems worth it ultimately.

Happy to take or leave either one, what do you think?

2018-02-07 18:59 UTC, djmitche commented
As long as this does add any new contradictions to the tools eslint config, I'm happy.

2018-02-07 21:59 UTC, djmitche requested changes
Maybe just add the spread for now?  We can try enabling recommended when we do the next spring cleaning.

2018-02-08 16:58 UTC, imbstack commented
Ok, I've removed the recommended rules and just added the experimental spread syntax.

2018-02-08 17:44 UTC, djmitche approved these changes

2018-02-08 17:46 UTC, merged